### ISSUE TITLE
Prepare Debugging Support for Other Languages for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/jsp-api#100]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by edbratt** [comment]
* javadoc and text updated - yes
* specification generated(https://github.com/eclipse-ee4j/jstl-api/tree/master/spec) - yes
(Note: No API JAR to release. Staging Release is n/a.

**Comment by m0mus** [comment]
https://github.com/jakartaee/specifications/pull/24
