### ISSUE TITLE
Prepare Jakarta Server Pages for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jsp-api#109]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by senivam** [comment]
TCK report for JSP-API: [[summary.txt](https://jenkins.eclipse.org/jsp/job/TCK_JSP_Bash/lastSuccessfulBuild/artifact/jsptck/src/com/sun/ts/tests/jsp/SUMMARY.TXT)]

**Comment by senivam** [comment]
JSP-API staging reference: [[2.3.6](https://oss.sonatype.org/content/groups/staging/jakarta/servlet/jsp/jakarta.servlet.jsp-api/2.3.6/)]

**Comment by arjantijms** [comment]
TCK report for Jakarta Server Pages against staged build: [summary.txt](https://jenkins.eclipse.org/jsp/view/Release/job/2_jsp-run-tck-against-staged-build/lastSuccessfulBuild/artifact/jsptck/bin/summary.txt/*view*/)

**Comment by m0mus** [comment]
@ren-zhijun-oracle What's the status of submitting a PR to jakartaee/specifications repository?

**Comment by ren-zhijun-oracle** [comment]
@m0mus I have not do it yet, I thought your team will take care of it, if not, I can do it today.

**Comment by lukasj** [comment]
@edbratt I don't have permissions to check jakartaee/specifications, the PR is: https://github.com/jakartaee/specifications/pull/77

**Comment by m0mus** [comment]
@lukasj What do you mean? You don't need special permissions to submit a PR.

**Comment by lukasj** [comment]
and PR for the API project: https://github.com/eclipse-ee4j/jakartaee-api/pull/28

@m0mus I don't have permissions to check checkboxes next to the "Create a PR to jakartaee/specifications repository" and "Update the Jakarta EE API jar by submitting a PR to the jakartaee-api project" in the description of this issue
