### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Debugging Support for Other Languages

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/jsp-api#113]
- [x] Organization Name ("Organization") and, if applicable, URL
Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
EE4J implementation of Jakarta Debugging Support for Other Languages, 1.0
- [x] Specification Name, Version and download URL
Jakarta Debugging Support for Other Languages 1.0
- [x] TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta Debugging Support for Other Languages TCK 1.0.0](https://download.eclipse.org/jakartaee/debugging/1.0/eclipse-debugging-tck-1.0.0.zip), SHA-256: c15d41a6d34c844d34ea846bd0ed6b5baa0d85cbfc3d05209e4df955ef7a5df7
- [x] Public URL of TCK Results Summary
[TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-debugging/1.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements
None
- [x] Java runtime used to run the implementation
Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...
 Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL.](https://www.eclipse.org/legal/tck.php)
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by starksm64** [comment]
TCK summary results link is broken

**Comment by edbratt** [comment]
Results summary link seems fixed. This looks good to me. Ok to accept and close?

**Comment by m0mus** [comment]
Accepted by Lazy Consensus.
