### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Server Pages

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jsp-api#115]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  [GlassFish 5.1](https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-5.1.0.zip)
- [x] Specification Name, Version and download URL\
   [Jakarta Server Pages 2.3](https://jakarta.ee/specifications/pages/2.3/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta Server Pages TCK 2.3.0](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-pages-tck-2.3.0.zip), SHA-256: 38dc605251653f6ec69a6f3c3f5fb678f0e4305a9abd8a7e47781c1ebad0e7e8
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-pages/2.3/TCK-Results), https://github.com/eclipse-ee4j/glassfish/pull/22808, https://github.com/eclipse-ee4j/glassfish/pull/22830
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by bshannon** [comment]
I'm declaring this approved by lazy consensus.
