### ISSUE TITLE
Deliver jsp-api Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jsp-api#129]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
- [x] **Initiate a ballot for your Jakarta Release Record/Plan.**
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by pnicolucci** [comment]
Release Record for 3.0.0 can be found here: https://projects.eclipse.org/projects/ee4j.jsp/releases/3.0.0

**Comment by mbroz2** [comment]
Taking a look at this one.

**Comment by kwsutter** [comment]
Since the javax -> jakarta spec checklist item was checked off, I'm also assuming that the overall spec has completed it's initial "jakarta-izing".  So, I'm marking that checklist item as well.  Thanks!

**Comment by kwsutter** [comment]
One last request for the Specifications PR to promote the Milestone deliverables for this Project.  The PR is created against the [Jakarta EE specifications github repo](https://github.com/jakartaee/specifications/pulls).  A template is automatically used when creating PRs against this repo which should help with understanding the steps required for a successful merge.  We're not looking for perfection for this Milestone.  We just want the ability to promote the great work that all of the Projects are doing.

If you submit a PR, please feel free to move this Epic to the [Milestone 1 Ready column in the Project Board](https://github.com/orgs/eclipse-ee4j/projects/17#column-9442495).  Thanks!

**Comment by markt-asf** [comment]
Almost ready. I'd really like to get https://github.com/eclipse-ee4j/jsp-api/pull/169 committed first and produce an RC. However, it time doesn't permit I should be able to do something with the M1 release.

**Comment by markt-asf** [comment]
https://github.com/jakartaee/specifications/pull/214
https://github.com/jakartaee/specifications/pull/215

**Comment by kwsutter** [comment]
Looking for an update on the status of the JSP Final Specification PR.  If we're going to make the [Sept deliverable goal](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9#jakarta-ee-9-schedule), then this Wave 2 Specification needs to be ready for final ballot by Monday, July 26.  Which means that the Specification PRs should already be created and under a "mentorship" review.  Can I ask what the plans are for this Specification?  Thanks!

**Comment by markt-asf** [comment]
The JARs should be available on staging. Just need to prepare PRs. I might be able to get to this later today unless someone beats me to it.

**Comment by markt-asf** [comment]
Sorry, I'm not going to be able to do this. Something isn't quite right with the staging / CI process. I previously added explicit staging profile IDs to get around issues with the wrong profile ID being used during CI (I think it was picking up the servlet staging profile rather than the JSP one). Someone who knows Maven and the Jakarta EE CI process better than me is probably best placed to fix this.

**Comment by joakime** [comment]
I can help once the internet/power is stable here in south texas (hurricane hannah just passed through).

**Comment by kwsutter** [comment]
The JSP PR was just discussed on the Platform Call...  Any updates on starting the final PRs for JSP?  Thanks!

**Comment by joakime** [comment]
Yes. I can start to look at it in about 3-ish hours.

**Comment by joakime** [comment]
The jsp-api 3.0.0 was staged to jakarta.oss.sonatype.org (repository ID `orgglassfishweb-1002`) back on July 23rd by @markt-asf 

The Job: https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/58/consoleFull

The `orgglassfishweb-1002` repository is present, and is successfully closed.

https://jakarta.oss.sonatype.org/content/repositories/orgglassfishweb-1002/

But here's were things go awry, that stage does not have the API, but only the impl??

Example: https://jakarta.oss.sonatype.org/content/repositories/orgglassfishweb-1002/org/glassfish/web/jakarta.servlet.jsp/3.0.0/

The build clearly indicates that it was to be deployed ...

```
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.0.0
[DEBUG] Tasks:   [clean, package, source:jar, javadoc:jar, gpg:sign, install:install, nexus-staging:deploy]
[DEBUG] Style:   Regular
```

and the `nexus-staging:deploy` succeeded for `jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.0.0`, but it's not present on the indicated staging respository, nor is it present in the aggregate/group "staging" repository.

https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/servlet/jsp/jakarta.servlet.jsp-api/

Something got really askew on ci.eclipse.org

**Comment by joakime** [comment]
This commit changed the nexus staging profileId (c71f5467e89ca658796cbb15129a3b80a2d93712) from `1c0c18a0fc339` to `a59edb2a44fc7`.

And that was used ... to deploy the IMPL only.

```
  <stagingProfileId>a59edb2a44fc7</stagingProfileId>
```

But that's not wholly correct to do, as the new stagingProfileId doesn't seem to result in something arriving at the staging repository.

The maven command line on the job currently looks like this ...

```
mvn -X -U -C -pl api,spec -DskipTests -Ddoclint=none -Poss-release -DstagingProfileId=3bda51d9c036 \
  clean package source:jar javadoc:jar -Dmaven.javadoc.failOnError=false gpg:sign \
  install:install nexus-staging:deploy --batch-mode \
  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
  -Poss-release -Pstaging
```

Which is `stagingProfileId=3bda51d9c036`

But that's not working.

It apparently used to be `1c0c18a0fc339` briefly ..  
* https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/jobConfigHistory/showDiffFiles?timestamp1=2020-06-13_12-06-22&timestamp2=2020-06-13_12-20-04
* https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/jobConfigHistory/showDiffFiles?timestamp1=2020-06-13_11-15-50&timestamp2=2020-06-13_11-32-53

And it was `3bda51d9c036` briefly ...
* https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/jobConfigHistory/showDiffFiles?timestamp1=2020-06-13_08-46-53&timestamp2=2020-06-13_09-15-52
* https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/jobConfigHistory/showDiffFiles?timestamp1=2020-02-13_03-44-48&timestamp2=2020-02-13_03-53-17
* https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/jobConfigHistory/showDiffFiles?timestamp1=2020-02-07_05-12-15&timestamp2=2020-02-13_03-44-48

Where did this staging Profile ID come from?
What's the correct one for JSP-API?
Come to think of it, why is this even declared as a number?
What on earth is this? (this is the very definition of a magic number)

Hard to fix this without the correct information.
At this point I'm stuck as well, there's nothing I can do to move things forward.

We need help from whomever is defining these stagingProfileIds, someone with login access to https://jakarta.oss.sonatype.org/ to actually be able to SEE THE STAGED REPOS (like anybody with login access to normal https://oss.sonatype.org/ can currently). - i tried with both my oss.sonatype.org login (that predates all of my eclipse logins), and also with my https://accounts.eclipse.org/ login (hoping that there was a auth path via those credentials. there wasnt).
Why is https://jakarta.oss.sonatype.org/ locked down like this?  It's just a needless impediment and puts all of the burden on eclipse webmaster to do things that can be resolved by merely having normal read access to the staging repository list.

**Comment by joakime** [comment]
Some more discoveries about the `stagingProfileId` that have been used / attempted in past builds.

The past ID's in use don't result in content on the repositoryId of `jakartaservletjsp-<num>` (as we would expect)

* profileId of `1c0c18a0fc339` results in content at repositoryId of `orgglassfish-<num>` (so that's a bad choice for jsp-api)
* profileId of `a59edb2a44fc7` results in content at repositoryId of `orgglassfish-<num>` (so that's a bad choice for jsp-api)

**Comment by joakime** [comment]
I opened PR https://github.com/eclipse-ee4j/jsp-api/pull/177 to revert these attempts to set the nexus `stagingProfileId`, as they don't work and/or produce undesired results.

We can try with the command line provided `stagingProfileId` instead once that's merged.

**Comment by joakime** [comment]
@kwsutter who tracks these `stagingProfileId` values? 
How can we get the correct one for our `jsp-api` staging?
This is a blocker and we cannot continue until we get the correct information.

**Comment by joakime** [comment]
@markt-asf looks like we have a valid stage now for version 3.0.0 of jsp-api.

Staging repository - https://jakarta.oss.sonatype.org/content/repositories/jakartaservletjsp-1018/

jsp-api artifact - https://jakarta.oss.sonatype.org/content/repositories/jakartaservletjsp-1018/jakarta/servlet/jsp/jakarta.servlet.jsp-api/3.0.0/

**Comment by joakime** [comment]
Requested a review of the staged jsp-api
https://www.eclipse.org/lists/jsp-dev/msg00135.html

**Comment by kwsutter** [comment]
@joakime Sorry, been on vacation...  I use the same login for https://jakarta.oss.sonatype.org/ as https://oss.sonatype.org/.  If that doesn't work for you, then I believe all you need to do is to create an issue asking for access.  It looks like this is what I had to do some time ago... https://issues.sonatype.org/browse/OSSRH-55577?filter=-2

Concerning the staging ids... It also looks like I had an [issue](https://issues.sonatype.org/browse/OSSRH-50982?filter=-2) with this when the Platform was first being built and deployed.  (Note this was back with the old repo, not this new jakarta repo.)  Everything should have been transferred to the new repository.  So, I would have assumed that the Ids for JSP would have transferred to the new repo.  But, maybe something was missed.

Sorry that you are hitting difficulties with this!  The more recent comments look like maybe you are past these initial hurdles and you're making progress?  Let me know if I can help out with getting the JSP PRs ready...  Thanks!

**Comment by arjantijms** [comment]
I just re-staged the API, which now includes the fixed automatic module ID (cc @keilw )

https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/jakarta.servlet.jsp-api/3.0.0/

(numbered repo: https://jakarta.oss.sonatype.org/content/repositories/jakartaservletjsp-1019/)

@joakime You did PR #177 to the 3.0.0 branch, which is the branch created by the CI and gets overwritten whenever a version is re-staged. The explicit profile ID is still in the pom in master.

My guess is that the issue with the staging seen before is the implicit profile selection strategy of Nexus. Maybe jakarta.servlet matched first in the order when jakarta.servlet.jsp-api is staged.

It's only a guess, but perhaps the order should start with the most specific one to the least specific one, so:

* https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/jstl/
* https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/
* https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/

The problem doesn't seem to be there now (as I just re-staged the API without issues, perhaps due to the explicit ID in the pom), but if it comes up again we'd probably best create an issue with sonatype.

Being able for us to login to https://jakarta.oss.sonatype.org should be good regardless, did you ever get the credentials for this?

**Comment by arjantijms** [comment]
Btw, the IDs can be requested using the Maven nexus plugin. I added an option for that in the jenkins build-and-stage job. The output is:

```
[INFO] Getting list of available staging repositories...
[INFO] 
[INFO] ID                   State    Description                   
[INFO] jakartaservletjsp-1006 OPEN     Implicitly created (auto staging).
[INFO] jakartaservletjsp-1005 CLOSED   jakarta.servlet.jsp:jakarta.servlet.jsp-api:2.3.6
[INFO] jakartaservletjsp-1015 CLOSED   jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:2.0.0-RC2
[INFO] jakartaservletjsp-1016 CLOSED   jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:2.0.0-RC3
[INFO] jakartaservletjsp-1017 CLOSED   jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:2.0.0
[INFO] jakartaservletjsp-1019 CLOSED   jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.0.0
[INFO] orgglassfishweb-1001 CLOSED   org.glassfish.web:jakarta.servlet.jsp.jstl:2.0.0-M2
[INFO] orgglassfishweb-1002 CLOSED   org.glassfish.web:jakarta.servlet.jsp:3.0.0
[INFO] ------------------------------------------------------------------------
[INFO] Getting list of available staging profiles...
[INFO] 
[INFO] ID              Mode   Name                          
[INFO] 16f2ccbfe56d73  BOTH   jakarta.jdsol                 
[INFO] 3bda51d9c036    BOTH   jakarta.servlet.jsp           
[INFO] a59edb2a44fc7   BOTH   org.glassfish.web    
```

**Comment by kwsutter** [comment]
Bump... Asking about the status of the JSP Specification draft PR.  @kazumura is the assigned Spec Committee member that can help with any questions.  And, since @arjantijms is involved with this, he's quite experienced with creating and pushing these Spec PRs through the process.  We have three remaining, missing draft PRs (JSF, JSP, and JSTL).  Thanks for your assistance!

**Comment by pnicolucci** [comment]
I just created the following PR for the Debugging 2.0 specification updates: https://github.com/jakartaee/specifications/pull/279

**Comment by pnicolucci** [comment]
I just created the following PR for the Pages 3.0 specification updates: https://github.com/jakartaee/specifications/pull/280

**Comment by arjantijms** [comment]
Result of ballot: https://eclipse.org/lists/jakarta.ee-spec/msg01303.html

**Comment by arjantijms** [comment]
Release bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=568078

**Comment by markt-asf** [comment]
All done.
