### ISSUE TITLE
Missing 2.3.6 implementation JAR

### ISSUE THREAD

**Issue by manorrock** [eclipse-ee4j/jsp-api#142]
It looks like the 2.3.6 implementation JAR never made it to Maven Central

**Comment by arjantijms** [comment]
After a quick investigation:

```
2.3.4 used old coordinates for implementation
2.3.4 used new coordinates for API
2.3.5 used new coordinates for implementation
2.3.5 used new coordinates for API, but is not TCK compliant (@Deprected added)
2.3.6 used new coordinates for API
2.3.6 no implementation release
```

**Comment by arjantijms** [comment]
cc @m0mus

**Comment by m0mus** [comment]
I see that 2.3.5 is integrated to GlassFish:

```
<jsp-api.version>2.3.5</jsp-api.version>
<jsp-impl.version>2.3.5</jsp-impl.version>
```

Version 2.3.5 is also mentioned here:
https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker

If 2.3.6 implementation is not released we should ask the project team to release it. 
@markt-asf ^^^

**Comment by arjantijms** [comment]
2.3.5 was the last version under Java EE 8 in GlassFish 5.1. 

2.3.6 is released under Jakarta EE 8, and not integrated in any official GlassFish release, but that shouldn't have prevented the impl part from being released I guess.

**Comment by markt-asf** [comment]
My focus at Jakarta EE is on specs, APIs and TCKs; not implementations. If someone wants to make a 2.3.6 implementation release I am not going to get in their way but it isn't something I have the time to do.

**Comment by manorrock** [comment]
@m0mus @markt-asf @arjantijms @pzygielo @Cousjava @kwsutter So who is going to do the release? Because as it stands right now the JSP implementation publicly available is NOT TCK compliant!

**Comment by manorrock** [comment]
@m0mus @markt-asf @arjantijms @pzygielo @Cousjava @kwsutter So who is going to do the release? Because as it stands right now the JSP implementation publicly available is NOT TCK compliant!

**Comment by manorrock** [comment]
@edbratt @ren-zhijun-oracle As Mark is saying he does not have time for a release can we get a release done by Zhijun as he is also listed as project lead?

**Comment by m0mus** [comment]
@edbratt I think he is not in Oracle anymore. I'll ask some of my folks to do it.

**Comment by Tomas-Kraus** [comment]
well, there is 2.3.6-RELEASE tag. I can restore all artifacts and send them to maven central

**Comment by m0mus** [comment]
Please make sure that it's buildable and tests are passing.

**Comment by Tomas-Kraus** [comment]
I need https://github.com/eclipse-ee4j/jsp-api/pull/143 to be merged first because of EF/OSSRH infrastructure changes

**Comment by arjantijms** [comment]
@Tomas-Kraus I merged #143 for the 2.3.6 branch. Thx!

**Comment by Tomas-Kraus** [comment]
Unfortunately I missed that API project depends on ee4j parent too. Need to merge PR https://github.com/eclipse-ee4j/jsp-api/pull/144

**Comment by Tomas-Kraus** [comment]
I was finally able to stage API artifacts: https://ci.eclipse.org/jsp/job/jsp-api-stage/4/consoleFull
We have jakartaservletjsp-1002 in staging repo.

**Comment by markt-asf** [comment]
API? I thought the issue was that there was no 2.3.6 implementation?

**Comment by arjantijms** [comment]
@Tomas-Kraus @markt-asf Indeed, we need the implementation. That's the one missing.

**Comment by Tomas-Kraus** [comment]
Yes, got it too. Prepared https://ci.eclipse.org/jsp/job/jsp-impl-stage/ job to do it.
Unfortunately parent pom is wrong again. Fixed by PR https://github.com/eclipse-ee4j/jsp-api/pull/145

**Comment by Tomas-Kraus** [comment]
Here it is: PR https://github.com/eclipse-ee4j/jsp-api/pull/146

**Comment by Tomas-Kraus** [comment]
So even artifact id change to match 3.0.0 did not help. Have to file a bug to OSSRH.

I restored original 2.3.6-RELEASE tag which points to revision that was used to release 2.3.6 API.
Now we have to wait for Sonatype to fix deployment permissions.

**Comment by Tomas-Kraus** [comment]
Passing link to OSSRH issue: https://issues.sonatype.org/browse/OSSRH-55370

**Comment by Tomas-Kraus** [comment]
So while waiting for Sonatype, I need to resolve another problem: TCK tests. https://ci.eclipse.org/jsp/job/2_jsp-run-tck-against-staged-build/ job works for API, but does not replace impl module in GF. I'll modify it to replace both artifacts (jakarta.servlet.jsp-api.jar and jakarta.servlet.jsp.jar).

**Comment by Tomas-Kraus** [comment]
OSSRH issue is resolved, IMPL 2.3.6 is in staging. So running TCK tests now.

**Comment by Tomas-Kraus** [comment]
Unfortunately TCK tests are failing during test initialization when being deployed to GF:
https://ci.eclipse.org/jsp/job/2_jsp-run-tck-against-staged-build/22/console

**Comment by Tomas-Kraus** [comment]
Problem with GF deployment of TCK tests resolved in https://github.com/eclipse-ee4j/jsp-api/pull/147

**Comment by Tomas-Kraus** [comment]
TCK tests passed: https://ci.eclipse.org/jsp/job/2_jsp-run-tck-against-staged-build/27/

**Comment by Tomas-Kraus** [comment]
IMPL 2.3.6 released: https://ci.eclipse.org/jsp/job/3_jsp-api-staging-to-release/4/console

**Comment by arjantijms** [comment]
Since impl is released, closing issue. Thx @Tomas-Kraus!
