### ISSUE TITLE
Release of 3.0.0-M1 Implementation Needed

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/jsp-api#152]
For further development of GlassFish 6.0.0 we need at least a milestone release of the 3..0.0-M1 implementation. The API is released to maven central but there is not release of the implementation.

**Comment by markt-asf** [comment]
The package rename has been completed (well, there don't appear to be any errors in my IDE) but I am not sure what state the implementation is overall. I have limited time so I am focusing my time on the parts that matter to me - the API, the specification document and the TCK.
@arjantijms indicated a desire to move this forward. There haven't been any commits since. I don't know if that is because Arjan hasn't had the time or it s simply that there is nothing to do.
There is milestone release of [Apache Tomcat's Jakarta EL 4.0 implementation](https://search.maven.org/artifact/org.apache.tomcat/tomcat-jasper-el/10.0.0-M3/jar) available on Maven Central if that is any help to you in the short term.

**Comment by arjantijms** [comment]
Last two weeks have been utterly mental, so it's purely a lack of time issue. I'll look at this one soon though.

**Comment by smillidge** [comment]
Jakarta EE 9 can't be released without GlassFish and I'm blocked on this currently. I can do a PR if a PR is needed but I can't merge or run Jenkins jobs.

**Comment by markt-asf** [comment]
Sorry, got my EL and JSP folders mixed up. Unlike the EL implementation, Tomcat's Jakarta EE 9 JSP implementation is unlikely to be a drop in replacement for Glassfish.

**Comment by markt-asf** [comment]
Also, the package rename hasn't been completed for the JSP impl. If someone wants to put together a PR for that I'm willing to approve/commit it providing it passes a basic sanity check.

**Comment by joakime** [comment]
I opened PR #153 to attempt this change to the codebase.

AFAICT, `/api/` was already converted.
Only the `/impl/` tree needed work.

**Comment by joakime** [comment]
The master branch now has the `javax.*` -> `jakarta.*` namespace change present (from PR#153)

**Comment by smillidge** [comment]
Thanks it needs someone on the project now to poke Jenkins to get a release

**Comment by arjantijms** [comment]
As the requirements for Jakarta EE 9 are JDK 11 for the implementations, shall I set the minimal JDK version to 11?

And pros/cons?

**Comment by arjantijms** [comment]
(btw, the project currently doesn't compile using JDK 11 at all, so that should be fixed at least)

**Comment by joakime** [comment]
Why are the other projects doing bytecode at Java 8 for Jakarta EE 9 then?

**Comment by markt-asf** [comment]
Please see the [Jakarta EE 9 release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan). TL;DR - Java 8 is the minimum version for API projects.

**Comment by markt-asf** [comment]
While the implementations need to run on Java 11 to certify so they could switch to Java 11, I'd leave the minimum Java version for this impl as Java 8. I'm curious why it doesn't compile with Java 11 though.

**Comment by joakime** [comment]
I'll take a look at the java 11 compile issue.

**Comment by arjantijms** [comment]
@joakime I'm already looking at it, it's just Javadoc

**Comment by arjantijms** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (attach-javadocs) on project jakarta.servlet.jsp: MavenReportException: Error while creating archive: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] /Users/arjan/eclipse2019-06/workspace/jsp-api/impl/src/main/java/org/apache/jasper/runtime/TldScanner.java:61: error: unknown tag: taglib
[ERROR]  *   1. Via <taglib> elements in web.xml:
[ERROR]             ^
[ERROR] /Users/arjan/eclipse2019-06/workspace/jsp-api/impl/src/main/java/org/apache/jasper/runtime/TldScanner.java:63: error: unknown tag: taglib
[ERROR]  *      the <taglib> element.
[ERROR]             ^
[ERROR] /Users/arjan/eclipse2019-06/workspace/jsp-api/impl/src/main/java/org/apache/jasper/runtime/TldScanner.java:66: error: unknown tag: uri
[ERROR]  *      of it. The taglib is 'global' if it has the <uri>
etc etc etc
```

**Comment by arjantijms** [comment]
I'll also update the plug-ins to their latest versions, as older plug-ins tend to have more issues with  the newer JDKs

**Comment by joakime** [comment]
> @joakime I'm already looking at it, it's just Javadoc

I defer to you.
Yep, the javadoc rules are much more strict on Java 9+
Had about 80% of the codebase to update javadoc on Eclipse Jetty a few years ago when Java 9 first hit.

> ```
> [ERROR] /Users/arjan/eclipse2019-06/workspace/jsp-api/impl/src/main/java/org/apache/jasper/runtime/TldScanner.java:61: error: unknown tag: taglib
> [ERROR]  *   1. Via <taglib> elements in web.xml:
> ```

Just use ...

```
{@code <taglib>}
```

That should address those tags nicely.

**Comment by arjantijms** [comment]
@joakime thanks! In the meanwhile if you could take a look at this PR that would be great:

https://github.com/eclipse-ee4j/jsp-api/pull/154

(there's on more coming for the update versions and then one for the javadoc fixes, and if nobody minds code formatting to standard Jakarta rules)

**Comment by arjantijms** [comment]
@smillidge 
> Thanks it needs someone on the project now to poke Jenkins to get a release

Jenkins poked: https://repo1.maven.org/maven2/org/glassfish/web/jakarta.servlet.jsp/3.0.0-RC1 ;)
