### ISSUE TITLE
Remove the automatic module name

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jsp-api#178]
The automatic module name does not comply with the JPMS module naming conventions as it has "api" at the end.
Since this was not present in Jakarta EE 8 yet either, the recommendation by the Spec Committee is to remove it from the POM and revisit the module name (automatic or fully qualified module-info) after Jakarta EE 9.

**Comment by joakime** [comment]
Where are these recommendations by the Spec Committee?
Got a link?

**Comment by keilw** [comment]
Here but please don't edit the document, it was created a bit "optimistic" https://docs.google.com/document/d/1LAAHKPJyREky9fEKv0xFd9IRDgXB58It53ryfyrNPtg/edit?usp=sharing
Option F is the preferred if not mandated one by the Spec Committee after some discussion.
"Do not create new Automatic Module Names for Jakarta EE 9". Websockets did not have one in Jakarta EE 8, therefore it should be removed.

**Comment by arjantijms** [comment]
I fixed the automatic id here: #179

If it needs to be removed instead, let me know.

**Comment by keilw** [comment]
We talked about them in the platform call and except Websocket all the others (especially EL, JSP and JSTL) seem good now. Using the package names are the best option for now, if Jakarta EE 10 or above really suddenly came up with a whole new naming convention of its own, then every single spec would have to change.
