### ISSUE TITLE
Spec document  contains "Jakarta Server Pages (JSP)"

### ISSUE THREAD

**Issue by pnicolucci** [eclipse-ee4j/jsp-api#184]
I had brought this up on the mailing list and creating this as a place holder so we don't forget about these changes : [Mailing list thread](https://www.eclipse.org/lists/jsp-dev/msg00131.html)

**Comment by hussainnm** [comment]
As per the [Acronym Guidelines](https://jakarta.ee/legal/acronym_guidelines/), it would be better to have a line in the Preface section of the document like "References in this document to JSP refer to the Jakarta Server Pages unless otherwise noted"

**Comment by pnicolucci** [comment]
I'd like to pull this into the final spec before we finish the draft PR:  https://github.com/jakartaee/specifications/pull/280
