### ISSUE TITLE
Compatibility Certification Request, Jakarta Debugging Support for Other Languages 2.0, Eclipse GlassFish 6

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jsp-api#185]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Foundation

- [x] Product Name, Version and download URL (if applicable):<br/>
  [Eclipse GlassFish 6.0](https://eclipse-ee4j.github.io/glassfish/download)
  [glassfish-6.0.0-M2-servlet5](https://github.com/eclipse-ee4j/glassfish/releases/tag/6.0.0-M2-servlet5)

- [x] Specification Name, Version and download URL:<br/>
   [Jakarta Debugging Support for Other Languages, 2.0](https://jakarta.ee/specifications/debugging/2.0/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta Debugging TCK 2.0](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-debugging-tck-2.0.0.zip)
  SHA-256: ` 71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc`

- [x] Public URL of TCK Results Summary:<br/>
  https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-debugging/2.0/TCK-Results

- [x] Any Additional Specification Certification Requirements:<br/>
  None

- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_191

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Cent OS Linux 7

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by joakime** [comment]
This issue seems mis-filed, how does this relate to jsp?

Also, jsp-api has no connection back to glassfish (meaning jsp-api doesn't use glassfish, but glassfish uses jsp-api, it's a one way relationship).

**Comment by markt-asf** [comment]
JDSOL is managed as part of this project (primarily I suspect because JSP implementations are the only place the spec is implemented).

**Comment by joakime** [comment]
TIL

**Comment by ivargrimstad** [comment]
Please add a label called `certification` so it is easy to find later if needed.

**Comment by markt-asf** [comment]
@edbratt Please see https://github.com/jakartaee/specifications/pull/237#discussion_r501302771
The binary referenced in this CR is not valid.

**Comment by edbratt** [comment]
Debugging support is being tested in each weekly release and the implementation validated by the TCK hasn't changed. We could update it to the latest GlassFish weekly release (where is is also [verified to pass](https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/98/junit-reports-with-handlebars/test-summary/bd1477aa-892c-439f-bb95-9b688d9653cc.html)): https://download.eclipse.org/ee4j/glassfish/weekly/glassfish-6.0.0-SNAPSHOT-2020-10-11.zip

**Comment by markt-asf** [comment]
It has been far more than 2 weeks required for lazy approval.  LGTM.
