### ISSUE TITLE
Compatibility certification request for Jakarta Server Pages 3.0

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jsp-api#190]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [EE4J implementation of Jakarta Server Pages 3.0.0](https://github.com/eclipse-ee4j/jsp-api/releases/download/3.0.0-RELEASE-impl/jakarta.servlet.jsp-3.0.0.jar)
  Vehicle: [GlassFish 6.0](https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-RC1.zip)
- [x] Specification Name, Version and download URL
   [Jakarta Server Pages 3.0](https://jakarta.ee/specifications/pages/3.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Server Pages TCK 3.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-pages-tck-3.0.0.zip), SHA-256: 2c90e6896d8321b82521a84746d6db5ee900af31b7850869b890dfde08fee8af
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-pages/3.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Alpine Linux v3.12
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by joakime** [comment]
Why did the staged jsp-api 3.0.0 go to the glassfish staging repo directly?
Shouldn't it go to the jsp specific staging repo?

From: https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/76/console

```
[INFO]  * Remote staging into staging profile ID "a59edb2a44fc7"
[INFO]  * Created staging repository with ID "orgglassfishweb-1005".
[INFO]  * Staging repository at https://jakarta.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/orgglassfishweb-1005
```

Other projects deploy to their application specific staging repo.

Example: From WebSocket  
https://ci.eclipse.org/websocket/job/1_websocket-api-build-and-stage/50/console

```
[INFO]  * Remote staging into staging profile ID "3baec0c0b757"
[INFO]  * Created staging repository with ID "jakartawebsocket-1010".
[INFO]  * Staging repository at https://jakarta.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/jakartawebsocket-1010
[INFO]  * Uploading locally staged artifacts to profile jakarta.websocket
```

**Comment by joakime** [comment]
I don't think JSP build bot can do the release/promote step from the glassfish staging repos.

**Comment by arjantijms** [comment]
> Why did the staged jsp-api 3.0.0 go to the glassfish staging repo directly?

The implementation goes to `orgglassfishweb`, since that are its Maven coordinates. The API goes to `jakartaservletjsp`.

**Comment by arjantijms** [comment]
> I don't think JSP build bot can do the release/promote step from the glassfish staging repos.

The JSP bot has access/privileges to both stage and release (to Central) for the following group ids:

* jakarta.jdsol                 
* jakarta.servlet.jsp           
* org.glassfish.web 

These group ids are not new, and we have released using them before, so we should be okay.

**Comment by joakime** [comment]
> > Why did the staged jsp-api 3.0.0 go to the glassfish staging repo directly?
> 
> The implementation goes to `orgglassfishweb`, since that are its Maven coordinates. The API goes to `jakartaservletjsp`.

Correct, that I knew.
The linked build I showed is for the API, not the impl.

Example:
https://ci.eclipse.org/jsp/job/1_jsp-api-build-and-stage/76/console

```
[INFO] Performing local staging (local stagingDirectory="/home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/nexus-staging/staging")...
[INFO]  + Using server credentials "ossrh" from Maven settings.
[INFO]  * Connected to Nexus at https://jakarta.oss.sonatype.org:443/, is version 2.14.19-01 and edition "Professional"
[INFO]  * Using staging profile ID "a59edb2a44fc7" (configured by user).
[INFO] Installing /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/jakarta.servlet.jsp-3.0.0.jar to /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/nexus-staging/staging/a59edb2a44fc7/org/glassfish/web/jakarta.servlet.jsp/3.0.0/jakarta.servlet.jsp-3.0.0.jar
[INFO] Installing /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/pom.xml to /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/nexus-staging/staging/a59edb2a44fc7/org/glassfish/web/jakarta.servlet.jsp/3.0.0/jakarta.servlet.jsp-3.0.0.pom
[INFO] Installing /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/jakarta.servlet.jsp-3.0.0-sources.jar to /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/nexus-staging/staging/a59edb2a44fc7/org/glassfish/web/jakarta.servlet.jsp/3.0.0/jakarta.servlet.jsp-3.0.0-sources.jar
[INFO] Installing /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/jakarta.servlet.jsp-3.0.0-javadoc.jar to /home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/nexus-staging/staging/a59edb2a44fc7/org/glassfish/web/jakarta.servlet.jsp/3.0.0/jakarta.servlet.jsp-3.0.0-javadoc.jar
```

**Comment by arjantijms** [comment]
> The linked build I showed is for the API, not the impl.

The names might be confusing, but `jakarta.servlet.jsp-3.0.0.jar` is the implementation. Note that it installs:

`/home/jenkins/agent/workspace/1_jsp-api-build-and-stage/impl/target/jakarta.servlet.jsp-3.0.0.jar`

The API jar name is `jakarta.servlet.jsp-api-3.0.0.jar`.

The look quite similar, but notice that one has "-api" in it, and the other has not. This is a convention that several old Sun projects use, but certainly not all.

**Comment by joakime** [comment]
Ah. 
Yes, that was confusing.
I'm all good now. :-)

**Comment by markt-asf** [comment]
LGTM. Much more than 2 weeks for lazy consensus. No objections. So accepting (and closing).
