### ISSUE TITLE
Update Specification to remove references to "JSP"

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jsp-api#192]
JSP is an Oracle/JCP acronym for `Java Server Pages`.  We can not publicly use JSP to represent `Jakarta Server Pages`.  For Jakarta EE 9, we are following the suggestion [1] to just highlight the fact that (temporarily) JSP is being used to represent `Jakarta Server Pages`.  This was done in the Preface of the Specification.

In the next service release for Jakarta Server Pages (3.x or 4.0), the use of JSP to represent `Jakarta Server Pages` should be removed.  You can continue to use JSP to represent `Java Server Pages`, if necessary for historical reasons.  But, everything going forward should use the name spelled out -- `Jakarta Server Pages` or just `Server Pages`.

[1] For reference, here's the link to the [Oracle/JCP Acronym Usage guidelines](https://jakarta.ee/legal/acronym_guidelines/).

**Comment by joakime** [comment]
This would impact the archive names too, no?

No more `jsp-api` as a filename.

The maven coordinates as well.

It would also impact some of the spec given names for known locations of contents with the servlet spec.

Heck, it would even impact the web descriptor schema on the servlet spec, see `<servlet><jsp-file>` child-element.

It would even impact the servlet level default url-patterns of `*.jsp`

**Comment by arjantijms** [comment]
@joakime There's a (temp?) exception for this usage in code (non doc), archive and project names. 

Nevertheless we need to step up our game here. Project names like e.g. http://github.com/eclipse-ee4j/jsp-api haven't been addressed. I personally put in some effort to get JASPIC renamed to authentication (http://github.com/eclipse-ee4j/authentication) but I think that's one of the only projects.

**Comment by joakime** [comment]
I think someone proposed just "pages" as in "Jakarta Pages" as an option.

Wonder if that means `index.pages` and `login.pages` are in our future?

**Comment by arjantijms** [comment]
Why not indeed. If that has broad consensus in the community and the team we could definitely do that.

For now I guess we should address the low hanging fruit first. Indeed. remove the "jsp" term from the Maven artefacts, and the project.

**Comment by kwsutter** [comment]
According to the guidelines, the continued use of "jsp" in the repo name, maven coordinates, etc is acceptable.  Of course, if you wish to make those type of updates (like what @arjantijms has done for jsf, jaspic, and others), then that's bonus.  But, the guidelines are clear that this usage is okay.

Another clarification...  I just received confirmation from Oracle (via the Steering Committee mailing list) that the statement in the [guidelines](https://jakarta.ee/legal/acronym_guidelines/) is accurate:
_"If a specification document (or related materials) contains references to an Oracle/JCP acronym, include a sentence such as the following: “References in this document to JMS refer to the Jakarta Message Service unless otherwise noted."_

This is the approach we took with the JSP Spec for Jakarta EE 9.  We put a similar statement in the Preface indicating that JSP was referring to Jakarta Server Pages.

So, there is no push to resolve this issue now or even in the future.  I'll leave this issue open for now and let the JSP team decide how (or if) to act on it.  Thanks!

**Comment by markt-asf** [comment]
Given that there is no real innovation expected in the spec at this point (most of the changes are reacting to the implications of changes in the EL spec) I think it makes most sense to stick with the status quo. I'm therefore resolving this issue but we always have the option of re-opening it if the situation changes.
