### ISSUE TITLE
Completion steps for JDSOL 2.0

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jsp-api#193]
* Specification Committee Member...
 - [x] creates an issue in the specification project that includes the following checklist for the specification project team:
 
* JDSOL Specification Project Team...
 - [] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] n/a The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by markt-asf** [comment]
@ivargrimstad How can I confirm whether or not the required email has been sent to tck@eclipse.org ?

**Comment by ivargrimstad** [comment]
@markt-asf I'll check with Wayne as soon as Canada wakes up. I am actually not really sure if this applies to each compatible implementation of a single specification. To me, it feels like this is something required only for implementations of the platform specs. I'll get back to you!

**Comment by ivargrimstad** [comment]
@markt-asf You're all set. This particular checklist item is actually for the implementation. In this case, I think GlassFish was the compatible implementation for the certification request, so it is their responsibility to send the email. And it is enough that they send one for the Full/Web profile. I'll put "n/a" on this checklist item and make sure it is updated for future use.

**Comment by markt-asf** [comment]
Thanks. All done here then.
