### ISSUE TITLE
Add Frames/NoFrames to JavaDocs

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jsp-api#194]
The JavaDocs that are staged for ballot review do not include frame/noframe options -- this was available in the previous version (2.3). Please consider adding this, when the next update is produced.

**Comment by joakime** [comment]
The default javadoc generation is no-frames.

```
$ javadoc --help | grep frames
    --frames      Enable the use of frames in the generated output
    --no-frames   Disable the use of frames in the generated output (default)
```

Perhaps the `org.eclipse.ee4j:project` parent should specify the ee4j defaults instead of making each project pick the wrong one.

**Comment by arjantijms** [comment]
Interesting indeed. A quick look at the other projects seems that most projects indeed just went with the defaults.

**Comment by joakime** [comment]
Ah.

The use of frames and the option to select frames vs no-frames is deprecated now in javadoc.

See: 

* https://bugs.openjdk.java.net/browse/JDK-8202961 - Javadoc should not generate frames by default
* https://bugs.openjdk.java.net/browse/JDK-8196202 - Update the javadoc/doclet to generate no frames as a default. A warning should be generated if "--frames" option is specified to generate frames. The support for frames will be removed from a future release.

I just confirmed, the ability to generate frames in javadoc is completely removed in OpenJDK 15 onwards.

**Comment by edbratt** [comment]
My comparison sample was against the previous version of Pages JavaDocs. If it is the consensus of the group this is not desirable, I'll go ahead and close this taking no action. It was considered and determined not needed.
