### ISSUE TITLE
Completion steps for Pages 3.0

### ISSUE THREAD

**Issue by kazumura** [eclipse-ee4j/jsp-api#195]
* Specification Committee Member...

- [x]  creates an issue in the specification project that includes the following checklist for the specification project team:

 * Pages Specification Project Team...

- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
- [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
specification API jar available in Maven Central: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jakarta.servlet.jsp-api/3.0.0

**Comment by arjantijms** [comment]
Mail sent. CC'ed @markt-asf

**Comment by arjantijms** [comment]
PR for the final item: https://github.com/eclipse-ee4j/jsp-api/pull/196

**Comment by markt-asf** [comment]
This is done.
