### ISSUE TITLE
Remove support for isThreadSafe

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jsp-api#206]
Servlet 6.0 is removing all code deprecated in Servlet 5.0 and earlier. This includes SingleThreadModel which means we need to remove support for `isThreadSafe`.

The specification document already carries a warning that this setting should be avoided so I think it is OK to remove it for this release. Since this impacts backwards compatibility do we want to increment the version to 4.0? It is a bit late in the day to do that but not impossible. An alternative would be to keep `isThreadSafe` but document it as a NO-OP regardless of setting. 

After thinking about it, I'm leaning towards making `isThreadSafe` a NO-OP.

**Comment by markt-asf** [comment]
Thinking about it some more, that could be problematic for any JSP currently marked as `isThreadSafe=false`. Removal and 4.0 is probably the better option.

**Comment by joakime** [comment]
I've been going through the code on github as a whole for users of `isThreadSafe=false` and seeing how they use it.

Search results: https://github.com/search?p=2&q=isThreadSafe+extension%3Ajsp&type=Code

So far, I've found ...

* TCK Tests
* Test cases in other projects (not mainline code)
* Main line code that has uses `isThreadSafe="false"` but also have not done anything else in the JSP that would warrant a `isThreadSafe` directive at all.

I'm trying to wrap my head around an example of `isThreadSafe="false"` in a real world application where things would fail if this was a no-op.

**Comment by joakime** [comment]
The history of the Servlet spec and threading ...

The `SingleThreadModel` was deprecated in Servlet 2.4, with no replacement, and wording in the spec that makes implementations of the Servlet spec not support `SingleThreadModel`.

Then Servlet 3.0 comes along with Async Processing and makes the case for `SingleThreadModel` even more untenable.

Then Servlet 3.1 comes along with Async I/O and further destroys the `SingleThreadModel` ability.

I would argue that the JSP support for `isThreadSafe="false"` has been unsupported and broken since Servlet 2.4.
Anyone using that directive since Servlet 2.4 hasn't actually had it working.

The last time Jetty supported `SingleTheadModel` was Jetty 4.x (which was EOL in 2006), Jetty 5.x no longer supported it. (with really nobody asking for it)

**Comment by joakime** [comment]
I think it's fair to NO-OP now, and document for removal in next version.
Going from supported to removal is a big harsh.

**Comment by joakime** [comment]
Do you actually spin up multiple Servlet instances when SingleThreadModel is used?

What do you do when a Servlet service method is synchronized by the application?
Do you assume SingleThreadModel and cause multiple instances of the Servlet? or just let the app run in a bad performance mode and a single standard Servlet instance?

**Comment by markt-asf** [comment]
> Do you actually spin up multiple Servlet instances when SingleThreadModel is used?

Yes.

> What do you do when a Servlet service method is synchronized by the application?
> Do you assume SingleThreadModel and cause multiple instances of the Servlet? or just let the app run in a bad performance mode and a single standard Servlet instance?

Tomcat does nothing so the app will (probably) perform badly.

**Comment by markt-asf** [comment]
I've been thinking about a couple of ways to avoid unexpected problems for those applications that are still using this:
- NO-OP (allow JSP compilation to continue without SingleThreadModel)
- log a warning and allow JSP compilation to continue without SingleThreadModel
- throw an exception

The more I think about this, the more I like throwing an exception as it is much safer. I'd rather a JSP didn't work at all than a JSP was used concurrently when it wasn't designed to be used that way. My primary concern is errors that go unnoticed.

**Comment by markt-asf** [comment]
Throwing the exception just brings us back to breaking stuff - which we were trying to void. We can;t use `SingleThreadModel` but we can synchronise the service method which will achieve the same result but with performance implications. That seems like a reasonable middle ground assuming we deprecate `isThreadSafe` with a view to removing it.
