### ISSUE TITLE
Make <jsp:plugin> No-OP

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jsp-api#226]
The API behind `<jsp:plugin>`, NPAPI has been removed from all major browsers. Also applets have been removed at the platform level.

While it is short notice, I intend to updates the Jakarta Pages spec for the 3.1 release as follows:

- containers will be expected to ignore (i.e. treat as a NO-OP) any `<jsp:plugin>` tags present in JSP pages
- the TCK will be updated to check these are ignored rather than generate `OBJECT` / `EMBED` tags.

**Comment by joakime** [comment]
I'm in agreement :+1:
