### ISSUE TITLE
Compatibility certification request for Jakarta Server Pages 3.1

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jsp-api#227]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Eclipse WaSP 3.1.0-M3](https://github.com/eclipse-ee4j/wasp)
  Vehicle: [Eclipse Glassfish 7.0.0-28-04-2022](https://github.com/eclipse-ee4j/glassfish/releases/download/7.0.0-28-04-2022/glassfish.zip) 
- [x] Specification Name, Version and download URL
   [Jakarta Server Pages 3.1](https://jakarta.ee/specifications/pages/3.1/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Server Pages TCK 3.1](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0.zip),  SHA-256: `e9f33d463ca35bdf8a9985cc8871858d7e6ea8a6e90adb00a91a001b1e43e025`
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-pages/3.1/TCK-Results)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  OpenJDK 11.0.2, 17.0.1, 18-ea
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Debian GNU/Linux 10
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by markt-asf** [comment]
Sorry, but you are going to need to re-run the TCK once it has been updated in light of #226. That should hopefully happen later today.

**Comment by arjantijms** [comment]
That's fine. Thanks for the heads-ups.
