### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsp-api#59]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by markt-asf** [comment]
We have the environment and I have created a basic job to build thew master branch but we are currently seeing errors. I have reached out on the ticket above for help.

**Comment by markt-asf** [comment]
We are now building master from api/pom.xml. That has highlighted some more Javadoc issues that need fixing. I'll open a separate issue for those but this task - creating the build for master - is done.
