### ISSUE TITLE
Fix Javadoc errors when building with Maven

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jsp-api#64]
```
cd api
maven clean install
```
results in a bunch of Javadoc errors. These need fixing.

**Comment by arjantijms** [comment]
Just for information, the JASPIC and JACC projects both had the same problem.

**Comment by markt-asf** [comment]
Not there yet. It looks like Jenkins is building with Java 9 which finds a bunch of extra errors. I'll put in a request to get multiple Java versions configured. I think we should build with at least the spec mandated minimum (currently Java 7 for JSP) and the latest. I'll also look at a PR to fix these additional issues with new Java versions.

**Comment by markt-asf** [comment]
Woot! The jdk-7 build is green:) I'll set up a separate build for jdk-latest. Still need to fix these Javadoc errors.

**Comment by markt-asf** [comment]
Jenkins is now building the JSP API with Java 7 and java latest (10.0.2) without error.
