### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsp-api#72]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by markt-asf** [comment]
The EE4J_8 branch is good to go as is the release build on Jenkins. I believe (correct me if I am wrong) we need to wait for the JakartaEE EL 3.0 release and then update our dependencies before we release the JSP API.

**Comment by vinayvishal** [comment]
PR #80 raised to update the dependencies to point to staged jakarta artifacts.

**Comment by vinayvishal** [comment]
Published to staging repository:
https://oss.sonatype.org/content/groups/staging/jakarta/servlet/jsp/jakarta.servlet.jsp-api/2.3.4/

**Comment by jansupol** [comment]
The API is missing in the Staging now. Can it be re-released?

**Comment by markt-asf** [comment]
Sign. I see Arjan re-ran the build. I'm just creating the Jenkins jobs I need to manipulate the staging repo.

**Comment by markt-asf** [comment]
And the RC is back in the staging repo.
