### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsp-api#90]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by arjantijms** [comment]
@markt-asf it's the "jsp-staging-to-release" job

**Comment by markt-asf** [comment]
@arjantijms You beat me to it. Just need to wait for it to appear in Maven Central.

**Comment by m0mus** [comment]
It cool to see a lot of activity on this task. Removing myself from assignees. :)

**Comment by arjantijms** [comment]
@markt-asf we worked together, as you did the dependency check which saved me from doing it ;) Thx!

**Comment by arjantijms** [comment]
JSP-API landed in central: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jakarta.servlet.jsp-api/2.3.4/
