### ISSUE TITLE
Update Scope Statement for Jakarta Server Pages Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jsp-api#94]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by chkal** [comment]
Draft:

> Jakarta Server Pages provides a specification document, API and TCK for a technology that helps software developers create dynamically generated web pages based on HTML, XML, or other document types.

This is based on the wording of the original [project proposal](https://projects.eclipse.org/projects/ee4j.jsp/reviews/creation-review).

**Comment by chkal** [comment]
It would be great to get some feedback by the committers of the project...

**Comment by arjantijms** [comment]
Maybe the scope should say something about JSP being a templating language, essentially.

JSF for instance also generates web pages based on HTML, XML, or other document types, but it clearly something completely different.

**Comment by arjantijms** [comment]
What something along these lines?

> Jakarta Server Pages provides a specification document, API and TCK for a technology that provides a template engine for web applications, which supports mixing of textual content (including HTML and XML) with custom tags, expression language and embedded Java code, and gets compiled into a Jakarta Servlet.

**Comment by markt-asf** [comment]
+1

**Comment by waynebeaton** [comment]
Let's focus on the specification itself (and skip the project for now).

> Jakarta Server Pages defines a template engine for web applications that supports mixing of textual content (including HTML and XML) with custom tags, expression language and embedded Java code, that gets compiled into a Jakarta Servlet.

Is the Servlet angle integral to the project? Is it important that all of this gets compiled into a Servlet, or is that just an implementation detail? i.e. does the specification itself require that everything gets compiled into a Servlet?

**Comment by markt-asf** [comment]
Yes.
`public interface JspPage extends Servlet { ...`

**Comment by arjantijms** [comment]
The JSP specification states this as well. See:

> JSP.11.1 JSP Page Model
> 
> A JSP page is represented at execution time by a JSP page implementation object and is executed by a JSP container. The JSP page implementation object is a servlet.

**Comment by waynebeaton** [comment]
So... do you want to go with this?

> Jakarta Server Pages defines a template engine for web applications that supports mixing of textual content (including HTML and XML) with custom tags, expression language, and embedded Java code, that gets compiled into a Jakarta Servlet.

**Comment by markt-asf** [comment]
+1

**Comment by waynebeaton** [comment]
I believe that we have consensus on:

> Jakarta Server Pages defines a template engine for web applications that supports mixing of textual content (including HTML and XML) with custom tags, expression language, and embedded Java code, that gets compiled into a Jakarta Servlet.

I'll take that to the Specification Committee for approval.
