### ISSUE TITLE
Jakarta EE 8 TCK job

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsp-api#98]
To test Jakarta EE 8 compatibility we need to create a Jenkins job on project's Cloud Jenkins instance formally testing the API against the relevant TCK and as needed, relevant CTS subset tests. 

For projects that do not already have automated testing, there is provided parameterized Jenkins job that can be invoked to perform these tests. User provides a link to an Eclipse GlassFish test build and sets the test sub-set parameters:

- For CTS -- https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/
- For Stand-alone TCKs -- https://ci.eclipse.org/jakartaee-tck/job/standalonetck-certification/

Additional instructions and guidance for using and directly running TCKs is available on [this wiki](https://wiki.eclipse.org/TCK:Build_From_Jakarta_EE_TCK_Repo_And_Run). Also in the [jakartaee-tck](https://github.com/eclipse-ee4j/jakartaee-tck) project repository.

**Comment by senivam** [comment]
***TCK standalone jobs for JSP-API***

prepare glassfish (integrate JSP): [TCK_build_glassfish](https://jenkins.eclipse.org/jsp/job/TCK_build_glassfish/)
prepare ts.jte config file (for JSP specific settings): [TCK_ts_jte_alter](https://jenkins.eclipse.org/jsp/job/TCK_ts_jte_alter/)
run TCK after previous jobs are done: [TCK_JSP_Bash](https://jenkins.eclipse.org/jsp/job/TCK_JSP_Bash/)

**Comment by senivam** [comment]
TCK CA Summary: [summary.txt](https://jenkins.eclipse.org/ca/job/TCK_CA_run/lastSuccessfulBuild/artifact/SUMMARY.TXT)
